### ISSUE TITLE
Feature: Possibility for integration with penumbra?

### ISSUE THREAD

**Issue by banana691** [BitsOfAByte/Travelcase#2]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

New feature

### Summary of the feature

Hi! Just wondering if it's possible to have an integration with penumbra? coz I don't have enough glamour plates for the extra zone glam I want (I barely have enough sets for my other glam sets ;-;).

Thanks!

### Why should this be added or changed?

It's for convenience and functionality with other 3rd party glams (yes, I want my bath towel glam in the bathroom XD)

**Comment by Blooym** [comment]
Would probably need to redesign a large amount of the plugin to accomplish something like this, but I can at least take a look to see if it's something I could do when I rework some stuff

**Comment by Blooym** [comment]
Its been a while and I haven't had the time to address this yet, but I've see a new plugin called [DynamicBridge](https://github.com/NightmareXIV/DynamicBridge/) come up lately that has the ability to apply Glamourer, Customize+ and Honorific presets on a more dynamic basis.

Take a look at it and let me know if it solves your problem. If it does then I will probably link to it in the README and not work on Penumbra support as it's already done there
