### ISSUE TITLE
Bug: Opening causes dalamud to crash 

### ISSUE THREAD

**Issue by Nullsloth** [BitsOfAByte/Travelcase#3]
Opening causes dalamud to crash. Guessing plugin is API 8 and not showing as outdated in installer. Thank you for this plugin I love it!

**Comment by Blooym** [comment]
The plugin was updated for API 9 pretty soon after it was made available to users. Can you please provide me your `dalamud.log` file so I can take a closer look? I'm unable to replicate a crash by opening the plugin both in-game and in the menus.

**Comment by Nullsloth** [comment]
The crash log or dalamud.log?

**Comment by Blooym** [comment]
`dalamud.log`

**Comment by Nullsloth** [comment]
None of these plugins are enabled. I disabled everything to troubleshoot. I attached the crashlog too if that is helpful at all.
[dalamud.log](https://github.com/Blooym/Travelcase/files/13254864/dalamud.log)
[dalamud_appcrash_20231103_164125_125_15324.log](https://github.com/Blooym/Travelcase/files/13254877/dalamud_appcrash_20231103_164125_125_15324.log)

**Comment by Blooym** [comment]
I cannot seem to cause the same issue to happen and the code itself doesn't seem out of the ordinary so I'm somewhat confused. I'll ask around to see if I can get an answer

**Comment by Blooym** [comment]
Hey, does this still occur now?
